# main.py
# Binary file parsing: https://github.com/googlecreativelab/quickdraw-dataset/blob/master/examples/binary_file_parser.py

from graphics import *
from harris import num_corners

import numpy as np
import random

import torch
from gan import batch_size, device, denorm
from architecture import latent_size, G, D


# window size
WIDTH = 500
HEIGHT = 500

IMAGE_SIZE = 28

COORD_SIZE = 125

NUM_SAMPLES = 2000

LABEL_CORNERS = False
NUM_LEVELS = 4

win = GraphWin("Bird Drawing Guesser", WIDTH, HEIGHT, autoflush=False)
win.setCoords(0, COORD_SIZE, COORD_SIZE, 0)
objects = [] # all objects currently drawn

padding = (COORD_SIZE - IMAGE_SIZE) / 2

# categories = ['duck', 'flamingo', 'owl', 'parrot', 'swan']
categories = ['duck']

# drawing: contains stroke information
def draw(drawing):
  i = 0
  for row in range(IMAGE_SIZE):
    for col in range(IMAGE_SIZE):
      if drawing[i] > 0:
        color = 255 - drawing[i]
        rect = Rectangle(Point(col + padding, row + padding), 
                        Point(col + 1 + padding, row + 1 + padding))
        rect.setFill(color_rgb(color, color, color))
        rect.setOutline(color_rgb(color, color, color))
        rect.draw(win)
        objects.append(rect)
      i += 1

# clear window
def clear():
  for obj in objects:
    obj.undraw()
  objects.clear()

def label_corners(corners):
  for corner in corners:
    c = Circle(Point(corner[0] + padding, corner[1] + padding), 0.5)
    c.setOutline("red")
    c.setWidth(0.5)
    c.draw(win)
    objects.append(c)

# gets data from all categories using corner detection method
# drawings are tuples of (image data, corner data)
def get_corner_data():
  result = {}
  for category in categories:
    print(category + ':')
    drawings = np.load('data/' + category + '.npy')
    # drawings = np.random.choice(drawings, size=NUM_SAMPLES, replace=False)
    drawings = drawings[:NUM_SAMPLES]

    # from low to high complexity
    levels = [[], [], []]

    # take random sample of drawings
    for drawing in drawings:
      corners, locs = num_corners(np.reshape(drawing, (-1, IMAGE_SIZE)))
      if corners < 150:
        levels[0].append((drawing, locs))
      elif corners > 250 and corners < 300:
        levels[1].append((drawing, locs))
      elif corners > 400 and corners < 450:
        levels[2].append((drawing, locs))

    print('Level 1: ' + str(len(levels[0])))
    print('Level 2: ' + str(len(levels[1])))
    print('Level 3: ' + str(len(levels[2])))
    result[category] = levels

  return result

# uses trained models to generate drawings for each category
def get_gan_images():
  result = {}
  for category in categories:
    random_vectors = torch.randn(batch_size, latent_size).to(device)
    G.load_state_dict(torch.load('model/g_' + category + '.pth'))
    G.eval()
    fake_images = G(random_vectors)
    fake_images = fake_images.reshape(fake_images.size(0), IMAGE_SIZE * IMAGE_SIZE)
    result[category] = (denorm(fake_images).detach().numpy() * 255).astype(int)
  
  return result


def main():
  print('Loading data...')
  data = get_corner_data()
  gan_data = get_gan_images()

  # game loop
  print('Hi! Welcome to Bird Drawing Guesser. Press enter to continue.')
  input()

  while True:

    print('Types of birds: ' + str(categories))

    random.shuffle(categories)

    for category in categories:
      print('What kind of bird is this?')
      for level in range(NUM_LEVELS):
        print()
        print('Level ' + str(level + 1))
        clear()

        if level < NUM_LEVELS - 1:
          if data[category][level]:
            arr = data[category][level]
          else:
            arr = data[category][1]
        else:
          print('Showing drawing generated by GAN!')
          print('Enter "gan" to generate another drawing!')
          arr = gan_data[category]
        
        drawing = arr[np.random.randint(len(arr))]
        draw(drawing[0] if level < (NUM_LEVELS - 1) else drawing)

        if LABEL_CORNERS and level < (NUM_LEVELS - 1):
          label_corners(drawing[1])

        val = input('Guess: ').lower().strip()
        while level >= (NUM_LEVELS - 1) and val == 'gan':
          clear()
          drawing = arr[np.random.randint(len(arr))]
          draw(drawing)
          val = input('Guess: ').lower().strip()

        if val == category:
          print('Correct!')
          break
        else:
          print('Incorrect.')
      print('This is a ' + category + '!')
      print('Press enter to continue.')
      input()

    val = input('Enter "q" to quit. Otherwise, continue playing! ').lower().strip()
    if val == 'q':
      break
  
  print('Thanks for playing!')
  
  win.close()

# trying to see how drawings are evaluated by the discriminator
def test():
  drawings = np.load('data/duck.npy').astype('float32')
  drawings = drawings[32000:]
  drawings /= 255.0
  drawings -= 0.5
  drawings /= 0.5
  D.load_state_dict(torch.load('model/d_duck.pth'))
  D.eval()
  
  for drawing in drawings:
    clear()
    drawing = torch.tensor(drawing)
    draw((denorm(drawing).numpy() * 255).astype(int))
    print(D(drawing))
    win.getKey()

if __name__ == "__main__":
  main()
  # test()
